# Generated by Django 3.1.1 on 2020-09-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_type', models.CharField(choices=[('I', 'Installation'), ('S', 'Sculpture'), ('FP', 'Found Photography')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.artwork')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='art_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.artworktype'),
        ),
    ]
