# Generated by Django 3.1.1 on 2020-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworktype',
            name='art_type',
            field=models.CharField(max_length=50),
        ),
    ]
